version: "3"

services:
  airflow:
    image: apache/airflow:latest

    volumes:
      - ./airflow:/opt/airflow
      - ./config.yaml:/opt/airflow/config.yaml:ro

    ports:
      - "8080:8080"
    command: airflow standalone

  metabase:
    image: metabase/metabase:latest
    container_name: workspace-metabase
    ports:
      - "3000:3000"
    volumes:
      - C:\workspace\airflow\sqlite:/sqlite:ro
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  metabase-data:
