version: "3"

services:
  airflow:
    image: apache/airflow:2.7.3

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}


    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"
    command: airflow standalone

  metabase:
    image: metabase/metabase:latest
    container_name: workspace-metabase
    ports:
      - "3000:3000"
    volumes:
      - C:\workspace\airflow\sqlite:/sqlite:ro
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  metabase-data:
